### ISSUE TITLE
Outdated NPM version

### ISSUE THREAD

**Issue by pavel** [zerkalica/modern-diff#2]
### Environment
Node.js: v6.3.1
NPM: v3.10.5
modern-diff: 0.2.0

### To reproduce:

In a new folder:
1. `npm install modern-diff`
2. Create `index.js` with the following content:
```javascript
var d = require('modern-diff');
```
3. Run `node index.js`

Problem:
```
module.js:442
    throw err;
    ^

Error: Cannot find module './diff'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/dev/Projects/diff/node_modules/modern-diff/dist/index.js:5:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

Possible cause:
Seems like NPM's version 0.2.0 was not built against relevant commit, leaving an old build in `dist` folder.

**Comment by zerkalica** [comment]
Fixed outdated npm build
